name: ${pluginName}
version: ${version}
main: ${group}.${packageName}.plugin.${pluginName}Plugin
api-version: 1.13
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.0
  - org.jetbrains.kotlin:kotlin-reflect:1.8.0